services:
  web:
    stdin_open: true
    tty: true
    container_name: animeeting_frontend
    build:
      context: .
      dockerfile: ./Dockerfile.web
    volumes:
      - ./application/:/opt/app
      - /opt/app/.next/
      - /opt/app/node_modules/
    ports:
      - '$PORT:3000'
    networks:
      - animeeting-network
    env_file:
      - .env
    environment:
      PORT: 3000
    healthcheck:
      test: curl --fail animeeting_frontend:3000/api/health || exit 1
      interval: 5s
      retries: 10
      start_period: 30s
      timeout: 10s
  redis:
    container_name: redis
    image: redis:7.2.4
    restart: always
    networks:
      - animeeting-network
    volumes:
      - redis_data_container:/var/lib/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  animeeting-network:
    name: animeeting-network
    driver: bridge

volumes:
  redis_data_container:
