# Dockerfile development version
FROM node:20.3.1-alpine AS animeeting

RUN apk -U upgrade && apk add --no-cache curl git bash

WORKDIR /opt/app

COPY application/package.json application/package-lock.json ./

RUN rm -rf node_modules && \
    rm -rf .next && \
    npm i

COPY application .

COPY entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["/usr/bin/entrypoint.sh"]

CMD ["npm", "run", "dev"]
